DROP TABLE IF EXISTS `CONVERSION`;

--
-- Create for table `CONVERSION`
--
CREATE TABLE `CONVERSION`
( `CON_FROMTO` varchar(50) NOT NULL,
  `CON_RATE`   double(50) NOT NULL,
  `CON_COUNT` int (10) NOT NULL,
  PRIMARY KEY(`CON_FROMTO`));

